; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
lib_ldf_mode = deep+

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
build_flags =
	-fno-exceptions
	-fno-rtti
	-Os
	-Wall
	-Wextra
	-DESP32
	-I include
	"-I${platformio.packages_dir}/framework-arduinoespressif32/libraries/LittleFS/src"
	"-I${platformio.packages_dir}/framework-arduinoespressif32/libraries/WiFi/src"
build_src_filter =
	+<*>
	-<hal/*_fake.cpp>
lib_deps =
	etlcpp/Embedded Template Library
	mobizt/ESP Mail Client@^3.4.24
	h2zero/NimBLE-Arduino
	paulstoffregen/OneWire
board_build.partitions = default.csv

[env:native]
platform = native
test_framework = doctest
extra_scripts = scripts/use_clang.py
build_flags = 
	-std=c++17
	-Wall
	-Wextra
	-fno-exceptions
	-fno-rtti
	-I src
	-I include
	-I test/test_skeleton
build_src_filter = 
	-<*>
	+<core/**>
	+<hal/*_fake.cpp>
build_type = debug
