#include "hal/display.h"

#include <cstdio>

#include <Arduino.h>
#include <lvgl.h>
#define LGFX_USE_V1
#include <LovyanGFX.hpp>

#include "Config.h"
#include "display_icons.h" // generated by tools/gen_display_icons.py

// Waveshare 1.9" ST7789 IPS 170x320 over SPI, landscape (320x170), rendered by
// LVGL v9 with LovyanGFX as the flush backend (DMA). All LVGL/LGFX state lives
// here as file-statics; nothing leaks into the header (link-time seam, NFR-06).
//
// Layout: house icon + inner temp (top row), landscape icon + outer temp or
// status text (bottom row), window-advice icon (open/closed) on the right.
//
// Threading: everything except setBrightness() runs on Core 1 only.

namespace {

class LGFX_Thermo final : public lgfx::LGFX_Device {
    lgfx::Panel_ST7789 panel_;
    lgfx::Bus_SPI      bus_;

  public:
    LGFX_Thermo() {
        auto b        = bus_.config();
        b.spi_host    = SPI2_HOST; // FSPI on ESP32-S3
        b.spi_mode    = 0;
        b.freq_write  = cfg::display::kSpiHz;
        b.spi_3wire   = false;
        b.use_lock    = false; // single-task access (Core 1 only)
        b.dma_channel = SPI_DMA_CH_AUTO;
        b.pin_sclk    = cfg::pin::kDispSclk;
        b.pin_mosi    = cfg::pin::kDispMosi;
        b.pin_miso    = -1;
        b.pin_dc      = cfg::pin::kDispDc;
        bus_.config(b);
        panel_.setBus(&bus_);

        auto p            = panel_.config();
        p.pin_cs          = cfg::pin::kDispCs;
        p.pin_rst         = cfg::pin::kDispRst;
        p.pin_busy        = -1;
        p.panel_width     = cfg::display::kPanelW; // 170
        p.panel_height    = cfg::display::kPanelH; // 320
        p.memory_width    = cfg::display::kMemW;   // 240 — ST7789 GRAM quirk
        p.memory_height   = cfg::display::kMemH;
        p.offset_x        = cfg::display::kOffsetX; // 35 — glass centred in GRAM
        p.offset_y        = 0;
        p.offset_rotation = 0;
        p.readable        = false;
        p.invert          = true; // mandatory on this IPS panel
        p.rgb_order       = false;
        p.bus_shared      = false;
        panel_.config(p);
        setPanel(&panel_);
    }
};

LGFX_Thermo s_gfx; // ctor only stores config; no HW access until init()

constexpr uint32_t kBufPx =
    static_cast<uint32_t>(cfg::display::kWidth) * cfg::display::kDrawBufLines;
// Static double buffers in internal RAM (.bss = DMA-capable; no PSRAM on board).
alignas(16) uint8_t s_buf1[kBufPx * 2U];
alignas(16) uint8_t s_buf2[kBufPx * 2U];

lv_display_t* s_disp{nullptr};
lv_obj_t*     s_lblInner{nullptr};
lv_obj_t*     s_lblStatus{nullptr};
lv_obj_t*     s_imgHouse{nullptr};
lv_obj_t*     s_imgLandscape{nullptr};
lv_obj_t*     s_imgWindow{nullptr};

// Layout (320x170 landscape) — small icons left, temp labels beside them,
// window-advice icon on the right.
constexpr int32_t kIconX   = 12;  // house + landscape icon column
constexpr int32_t kHouseY  = 16;  // house icon (44x44)
constexpr int32_t kLandY   = 106; // landscape icon (44x44)
constexpr int32_t kLabelX  = 66;  // temp label column
constexpr int32_t kRow1Y   = 14;  // inner temp (Montserrat 48)
constexpr int32_t kRow2Y48 = 104; // outer temp / FIRE! (Montserrat 48)
constexpr int32_t kRow2Y24 = 116; // SENSOR / WiFi DOWN (Montserrat 24)
constexpr int32_t kWindowX = 234; // window icon (84x108); flush right (2px margin) for a gap from the temp
constexpr int32_t kWindowY = 31;

// Colors.
constexpr uint32_t kColorTempHex = 0xFFFFFF; // white
constexpr uint32_t kColorFireHex = 0xFF3020; // red
constexpr uint32_t kColorWarnHex = 0xFFA020; // orange (SENSOR / WiFi DOWN)

void flushCb(lv_display_t* disp, const lv_area_t* area, uint8_t* px_map) {
    const int32_t w = lv_area_get_width(area);
    const int32_t h = lv_area_get_height(area);
    // v9 removed LV_COLOR_16_SWAP; swap to panel endianness here, then DMA.
    lv_draw_sw_rgb565_swap(px_map, static_cast<uint32_t>(w) * static_cast<uint32_t>(h));
    s_gfx.pushImageDMA(area->x1, area->y1, w, h, reinterpret_cast<const lgfx::swap565_t*>(px_map));
    // Safe with double buffering: LVGL renders into the other buffer while DMA
    // runs; the next pushImageDMA blocks until this transfer completes.
    lv_display_flush_ready(disp);
}

// "21.5°C" / "-12.3°C" from centi-degC without float. UTF-8 ° = "\xC2\xB0".
// The row identity (inner/outer) is carried by the house/landscape icons.
void fmtTemp(char* out, size_t n, Temperature c100) {
    if (c100 == kTempInvalid) {
        snprintf(out, n,
                 "--.-\xC2\xB0"
                 "C");
        return;
    }
    const bool    neg   = c100 < 0;
    const int32_t absC  = neg ? -static_cast<int32_t>(c100) : c100;
    const int32_t whole = absC / 100;
    const int32_t tenth = (absC % 100) / 10;
    snprintf(out, n,
             "%s%ld.%ld\xC2\xB0"
             "C",
             neg ? "-" : "", static_cast<long>(whole), static_cast<long>(tenth));
}

} // namespace

Result<void> Display::init() {
    s_gfx.init();
    s_gfx.setRotation(cfg::display::kRotation); // 320x170 landscape
    s_gfx.startWrite();                         // hold the bus: enables DMA overlap

    // Backlight: LEDC Timer 1 (buzzer owns Timer 0 — tone() cannot corrupt duty).
    ledcSetup(cfg::ledc::kBacklightChannel, cfg::ledc::kBacklightFreqHz,
              cfg::ledc::kBacklightResBits);
    ledcAttachPin(cfg::pin::kDispBacklight, cfg::ledc::kBacklightChannel);
    ledcWrite(cfg::ledc::kBacklightChannel, cfg::ledc::kBacklightDefault);

    lv_init();
    lv_tick_set_cb(+[]() -> uint32_t { return static_cast<uint32_t>(millis()); });

    s_disp = lv_display_create(cfg::display::kWidth, cfg::display::kHeight);
    if (s_disp == nullptr) {
        return Result<void>::err(Status::kNotReady);
    }
    lv_display_set_flush_cb(s_disp, flushCb);
    lv_display_set_buffers(s_disp, s_buf1, s_buf2, sizeof(s_buf1), LV_DISPLAY_RENDER_MODE_PARTIAL);

    lv_obj_t* scr = lv_screen_active();
    lv_obj_set_style_bg_color(scr, lv_color_black(), 0);

    s_imgHouse = lv_image_create(scr);
    lv_image_set_src(s_imgHouse, &kImgHouse);
    lv_obj_set_pos(s_imgHouse, kIconX, kHouseY);

    s_imgLandscape = lv_image_create(scr);
    lv_image_set_src(s_imgLandscape, &kImgLandscape);
    lv_obj_set_pos(s_imgLandscape, kIconX, kLandY);

    s_imgWindow = lv_image_create(scr);
    lv_image_set_src(s_imgWindow, &kImgWindowClosed);
    lv_obj_set_pos(s_imgWindow, kWindowX, kWindowY);

    s_lblInner = lv_label_create(scr);
    lv_obj_set_style_text_font(s_lblInner, &lv_font_montserrat_48, 0);
    lv_obj_set_style_text_color(s_lblInner, lv_color_hex(kColorTempHex), 0);
    lv_obj_set_pos(s_lblInner, kLabelX, kRow1Y);
    lv_label_set_text(s_lblInner, "");

    s_lblStatus = lv_label_create(scr);
    lv_obj_set_style_text_font(s_lblStatus, &lv_font_montserrat_48, 0);
    lv_obj_set_style_text_color(s_lblStatus, lv_color_hex(kColorTempHex), 0);
    lv_obj_set_pos(s_lblStatus, kLabelX, kRow2Y48);
    lv_label_set_text(s_lblStatus, "");

    return Result<void>::ok();
}

void Display::setBrightness(uint8_t duty) {
    ledcWrite(cfg::ledc::kBacklightChannel, duty);
}

void Display::render(const DisplayFrame& f) {
    if (!firstRender_ && f == cached_) {
        return; // no churn at 1 Hz with stable readings
    }
    firstRender_ = false;
    cached_      = f;

    char buf[20];
    fmtTemp(buf, sizeof(buf), f.innerC100);
    lv_label_set_text(s_lblInner, buf);

    switch (f.status) {
    case DisplayStatus::kFire:
        lv_obj_set_style_text_font(s_lblStatus, &lv_font_montserrat_48, 0);
        lv_obj_set_style_text_color(s_lblStatus, lv_color_hex(kColorFireHex), 0);
        lv_obj_set_pos(s_lblStatus, kLabelX, kRow2Y48);
        lv_label_set_text(s_lblStatus, "FIRE!");
        break;
    case DisplayStatus::kSensorFault:
        lv_obj_set_style_text_font(s_lblStatus, &lv_font_montserrat_24, 0);
        lv_obj_set_style_text_color(s_lblStatus, lv_color_hex(kColorWarnHex), 0);
        lv_obj_set_pos(s_lblStatus, kLabelX, kRow2Y24);
        lv_label_set_text(s_lblStatus, "SENSOR");
        break;
    case DisplayStatus::kWifiDown:
        lv_obj_set_style_text_font(s_lblStatus, &lv_font_montserrat_24, 0);
        lv_obj_set_style_text_color(s_lblStatus, lv_color_hex(kColorWarnHex), 0);
        lv_obj_set_pos(s_lblStatus, kLabelX, kRow2Y24);
        lv_label_set_text(s_lblStatus, "WiFi DOWN");
        break;
    case DisplayStatus::kOuterTemp:
        lv_obj_set_style_text_font(s_lblStatus, &lv_font_montserrat_48, 0);
        lv_obj_set_style_text_color(s_lblStatus, lv_color_hex(kColorTempHex), 0);
        lv_obj_set_pos(s_lblStatus, kLabelX, kRow2Y48);
        fmtTemp(buf, sizeof(buf), f.outerC100);
        lv_label_set_text(s_lblStatus, buf);
        break;
    }

    // Window advice icon: open when recommended, otherwise closed (two states only).
    lv_image_set_src(s_imgWindow, f.advice == window::Advice::kOpen ? &kImgWindowOpen
                                                                    : &kImgWindowClosed);
}

void Display::tick() {
    lv_timer_handler();
}
