#!/usr/bin/env python3
"""Embed web/ assets into a PROGMEM C++ header (src/app/web_assets.h).

Run after editing web/index.html or web/app.js:
    python tools/embed_web.py

The generated header holds each file as a raw string literal so the firmware can
serve them from flash without a filesystem.
"""
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
WEB = ROOT / "web"
OUT = ROOT / "src" / "app" / "web_assets.h"
DELIM = "WEBRAW"


def emit(symbol: str, path: pathlib.Path) -> str:
    text = path.read_text(encoding="utf-8")
    if f"){DELIM}\"" in text:
        raise SystemExit(f"raw-string delimiter {DELIM} collides with content of {path}")
    return f'inline const char {symbol}[] PROGMEM = R"{DELIM}(\n{text})' + f'{DELIM}";\n'


def main() -> None:
    parts = [
        "#pragma once",
        "// AUTO-GENERATED by tools/embed_web.py from web/*. Do not edit by hand.",
        "#include <pgmspace.h>",
        "",
        "namespace web_assets {",
        emit("kIndexHtml", WEB / "index.html"),
        emit("kAppJs", WEB / "app.js"),
        "} // namespace web_assets",
        "",
    ]
    OUT.write_text("\n".join(parts), encoding="utf-8")
    print(f"wrote {OUT} ({OUT.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
