#!/usr/bin/env python3
"""Generate src/hal/display_icons.h — icons/ PNGs as LVGL v9 image arrays.

Source PNGs (512x512 RGBA) live in icons/; each is downscaled (Lanczos) to its
display size, fitted with preserved aspect ratio (centered, padded), and
composited onto black. Because the screen background is pure black, build-time
compositing is mathematically identical to runtime alpha blending — so plain
RGB565 (2 B/px) suffices, no alpha plane needed.

  icons/house.png         -> kImgHouse        44x44
  icons/land.png          -> kImgLandscape    44x44
  icons/window_closed.png -> kImgWindowClosed 84x108
  icons/window_open.png   -> kImgWindowOpen   84x108

Output is little-endian RGB565 (LVGL native; the display flush callback does
the panel byte swap, so image data must stay unswapped).

Usage:  pip install pillow && python tools/gen_display_icons.py
"""

import os

from PIL import Image

ROOT = os.path.join(os.path.dirname(__file__), "..")
OUT = os.path.join(ROOT, "src", "hal", "display_icons.h")

ICONS = [
    ("kImgHouse", "house.png", 44, 44),
    ("kImgLandscape", "land.png", 44, 44),
    ("kImgWindowClosed", "window_closed.png", 84, 108),
    ("kImgWindowOpen", "window_open.png", 84, 108),
]


def load_fitted(path, w, h):
    """Downscale preserving aspect, center on a w x h black canvas."""
    src = Image.open(path).convert("RGBA")
    scale = min(w / src.width, h / src.height)
    fitted = src.resize(
        (max(1, round(src.width * scale)), max(1, round(src.height * scale))),
        Image.LANCZOS,
    )
    canvas = Image.new("RGBA", (w, h), (0, 0, 0, 255))
    canvas.alpha_composite(
        fitted, ((w - fitted.width) // 2, (h - fitted.height) // 2)
    )
    return canvas.convert("RGB")


def emit_image(name, img):
    w, h = img.size
    raw = img.tobytes()  # RGB, 3 bytes per pixel
    data = bytearray()
    for i in range(0, len(raw), 3):
        r, g, b = raw[i], raw[i + 1], raw[i + 2]
        v = ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)
        data.append(v & 0xFF)  # little-endian: low byte first
        data.append(v >> 8)
    lines = []
    for i in range(0, len(data), 24):
        chunk = data[i : i + 24]
        lines.append("    " + " ".join(f"0x{b:02X}," for b in chunk))
    body = "\n".join(lines)
    return f"""
alignas(4) static const uint8_t {name}Map[{len(data)}] = {{
{body}
}};

static const lv_image_dsc_t {name} = {{
    .header =
        {{
            .magic      = LV_IMAGE_HEADER_MAGIC,
            .cf         = LV_COLOR_FORMAT_RGB565,
            .flags      = 0,
            .w          = {w},
            .h          = {h},
            .stride     = {w * 2},
            .reserved_2 = 0,
        }},
    .data_size = sizeof({name}Map),
    .data      = {name}Map,
}};
"""


def main():
    parts = [
        "// display_icons.h — GENERATED by tools/gen_display_icons.py — DO NOT EDIT.\n"
        "// Source PNGs in icons/, downscaled + composited onto black at build time.\n"
        "// LVGL v9 RGB565 (native LE, unswapped — flush cb does the panel byte swap).\n"
        "#pragma once\n"
        "#include <cstdint>\n"
        "#include <lvgl.h>\n"
    ]
    total = 0
    for name, fname, w, h in ICONS:
        img = load_fitted(os.path.join(ROOT, "icons", fname), w, h)
        parts.append(emit_image(name, img))
        total += w * h * 2
    out = os.path.abspath(OUT)
    with open(out, "w", newline="\n") as f:
        f.write("".join(parts))
    print(f"wrote {out} ({total} bytes of pixel data)")


if __name__ == "__main__":
    main()
